version: '2'
services:
    siemcore-app:
        image: siemcore
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://siemcore-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=SIEMCore
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=siemcore-elasticsearch:9300
        ports:
            - 8080:8080
    siemcore-mongodb:
        extends:
            file: mongodb.yml
            service: siemcore-mongodb
    siemcore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: siemcore-elasticsearch
